from collections.abc import Callable, Mapping, Sequence
from pathlib import Path
from typing import TypeAlias, TypeVar, final

_T = TypeVar("_T")

_Position: TypeAlias = Sequence[int]
_FloatPosition: TypeAlias = Sequence[float]
_Ranges: TypeAlias = Sequence[tuple[int, int] | None]
_State: TypeAlias = tuple[str, dict[str, str]]
_Item: TypeAlias = tuple[str, int, str | None]

@final
class MinecraftData:
    def __new__(cls, cache_dir: Path | None = None, offline: bool = False) -> MinecraftData: ...
    def cache_dir(self) -> Path: ...
    def versions(self) -> list[str]: ...
    def load(self, version: str) -> str: ...
    def dataset(self, version: str, kind: str) -> str: ...
    def load_visuals(self, version: str) -> Path: ...

@final
class Schematic:
    def __new__(cls, edition: str, version: str, source: MinecraftData) -> Schematic: ...
    @staticmethod
    def from_bytes(
        data: bytes,
        format: str,
        source: MinecraftData,
        version: str | None,
        origin: _Position | None,
        palette: dict[str, str],
    ) -> Schematic: ...
    def to_bytes(
        self, format: str, allow_loss: bool, flatten: bool, version: str | None = None
    ) -> bytes: ...
    def check_export(
        self, format: str, flatten: bool, version: str | None = None
    ) -> tuple[list[str], list[str]]: ...
    def glb(self, region: str | None, ranges: _Ranges) -> tuple[bytes, list[str]]: ...
    def png(
        self,
        region: str | None,
        ranges: _Ranges,
        size: Sequence[int],
        view: str,
        grid: bool,
    ) -> tuple[bytes, list[str]]: ...
    def sprites(
        self,
        region: str | None,
        ranges: _Ranges,
        view: str,
        style: tuple[int, bool, bool],
        sprites: dict[str, str],
    ) -> tuple[bytes, list[str]]: ...
    def blueprint(
        self,
        name: str,
        region: str | None,
        y: tuple[int, int] | None,
        rotation: int,
        sprites: dict[str, str],
    ) -> tuple[str, list[str]]: ...
    def validate(self) -> tuple[list[str], list[str], list[str]]: ...
    def repair(
        self, rules: list[str] | None = None
    ) -> tuple[
        list[tuple[str, _Position, tuple[str, dict[str, str]], tuple[str, dict[str, str]]]],
        list[str],
    ]: ...
    def region(self, name: str) -> Region: ...
    def add_region(self, name: str, origin: _Position) -> Region: ...
    def regions(self) -> list[str]: ...
    def import_diagnostics(self) -> list[str]: ...
    def info(self) -> tuple[str, str, int]: ...
    def describe(self, id: str) -> str: ...
    def metadata(self) -> str: ...
    def set_metadata(self, snbt: str) -> None: ...

@final
class Region:
    def bounds(self) -> tuple[list[int], list[int]]: ...
    def origin(self) -> list[int]: ...
    def to_global(self, local: _Position) -> list[int]: ...
    def to_local(self, global_position: _Position) -> list[int]: ...
    def get(self, at: _Position) -> _State: ...
    def get_all(self, factory: Callable[[_State], _T]) -> dict[tuple[int, int, int], _T]: ...
    def set_many(
        self, palette: Sequence[_State], cells: Sequence[tuple[_Position, int]]
    ) -> None: ...
    def select(self, start: _Position, size: _Position) -> Selection: ...
    def set_fragment(self, at: _Position, fragment: Fragment) -> None: ...
    def place(self, placement: Placement, at: _Position, replace: bool) -> None: ...
    def block_entity_get(self, at: _Position) -> str | None: ...
    def block_entity_set(self, at: _Position, snbt: str) -> None: ...
    def block_entity_remove(self, at: _Position) -> None: ...
    def entity_add(
        self, id: str, persistent: bool, snbt: str | None, at: _FloatPosition
    ) -> int: ...
    def entity_list(self) -> list[int]: ...
    def entity_get(self, reference: int) -> tuple[list[float], str]: ...
    def entity_update(
        self,
        reference: int,
        position: _FloatPosition | None,
        snbt: str | None,
    ) -> None: ...
    def entity_remove(self, reference: int) -> None: ...

@final
class Selection:
    def bounds(self) -> tuple[list[int], list[int]]: ...
    def get_all(self, factory: Callable[[_State], _T]) -> dict[tuple[int, int, int], _T]: ...
    def select(self, id: str | None, properties: dict[str, str]) -> Selection: ...
    def fill(self, id: str, properties: dict[str, str]) -> None: ...
    def patch(self, properties: dict[str, str]) -> None: ...
    def delete(self) -> None: ...
    def move_by(self, offset: _Position, replace: bool) -> None: ...
    def rotate(
        self, axis: str, steps: int, pivot: _FloatPosition | None, replace: bool
    ) -> None: ...
    def flip(self, axis: str, center: float | None, replace: bool) -> None: ...
    def duplicate(self, offset: _Position, replace: bool) -> Selection: ...
    def copy(self) -> Fragment: ...
    def counts(self) -> dict[str, int]: ...
    def layer(self, y: int) -> list[tuple[list[int], str]]: ...

@final
class Fragment:
    def size(self) -> list[int]: ...

@final
class Placement: ...

def bed(*, color: str = "red", head_toward: str = "north") -> Placement: ...
def door(
    *,
    material: str = "oak",
    facing: str = "north",
    hinge: str = "left",
    open: bool = False,
    powered: bool = False,
) -> Placement: ...
def chest(*, facing: str = "north", items: Mapping[int, _Item] | None = None) -> Placement: ...
def sign(
    lines: Sequence[str],
    *,
    material: str = "oak",
    rotation: int = 0,
    color: str = "black",
) -> Placement: ...
